export const ActionTypes = {
    SET_PRODUCTS : 'SET_PRODUCTS',
    SELECTED_PRODUCT : 'SELECTED_PRODUCT',
    REMOVE_SELECTED_PRODUCT : 'REMOVE_SELECTED_PRODUCT',
    EDIT_SELECTED_PRODUCT : 'EDIT_SELECTED_PRODUCT',
    CREATE_PRODUCT:'CREATE_PRODUCT',
    CREATE_ORDER: 'CREATE_ORDER',
    SET_ORDERS: 'SET_ORDERS',
    ADD_TO_CART:'ADD_TO_CART',
    INCREMENT_CART:'INCREMENT_CART',
    DECREMENT_CART:'DECREMENT_CART',
    REMOVE_CART:'REMOVE_CART',
    SELECTED_ORDER:'SELECTED_ORDER',
    SET_NOTDELIVERED_ORDERS:'SET_NOTDELIVERED_ORDERS',
    SET_DELIVERED_ORDERS:'SET_DELIVERED_ORDERS',
    DELIVERED_ORDER:'DELIVERED_ORDER',
    SET_BASKET: 'SET_BASKET',
    SET_PRODUCTS_BY_CATEGORY:'SET_PRODUCTS_BY_CATEGORY'
};